-- do here what lua seemingly cannot yet do
-- except this does not work for what's here.
--vim.cmd [[
--    clipboard += "unnamed"
--    clipboard += "unnamedplus"
--
--    vnoremap("C-j>", "<cmd>m '>+1<CR>gv=gv")
--    vnoremap("C-k>", "<cmd>m '<-2<CR>gv=gv")
--]]
